### ISSUE TITLE
Save to Camera Roll: API for requesting save permission?

### ISSUE THREAD

**Issue by derwaldgeist** [natmlx/NatShare#118]
In our use-case, asking for the "album save permission" at the time-point when the image has to be saved leads to a pretty weird user experience. Thus, we would like to move this permission request to the user-settings, like WhatsApp does it. However, I could not see an API for just requesting the save permissions without actually saving an image to the system album. The only workaround would be to save a dummy image and delete it right afterwards, which is not the best solution. And there's also no API to delete the photo.

Thus, I'd love to see a separate API call for requesting the permission only, without actually saving anything.

**Comment by olokobayusuf** [comment]
This is a good feature request. I'll look into it.

**Comment by derwaldgeist** [comment]
Thanks Yusuf.

Another thing I'd like to point out: Since `NatShare` didn't offer a permission request so far, I was using yasirkula's `NativeShare`'s permission dialog instead. However, since I upgraded Xcode to the latest version targeting iOS 14+ and also had to update NativeShare along the way (the old version threw compile errors), I noticed that now NativeShare won't ask the user for access to a specific album anymore. This is because according to its docs, iOS 14+ only allows access to the general album.

This leads to a weird UX: If I ask for write access using `NativeShare`, only the general write permission popup shows. But if I later actually save a photo using `NatShare`, a second permission pops up (this time, only asking the user which album should be used). If I can trust the explanation of the `NativeShare` package, this addition permission would be useless, because iOS ignores the album anyways. So maybe `NatShare` should be adapted to reflect this change?

Of course, I could start using `NativeShare` instead, which also allows storing photos. However, I like the async interface of `NatShare`, so I would like to keep it.

**Comment by olokobayusuf** [comment]
> This leads to a weird UX: If I ask for write access using NativeShare, only the general write permission popup shows. But if I later actually save a photo using NatShare, a second permission pops up (this time, only asking the user which album should be used). If I can trust the explanation of the NativeShare package, this addition permission would be useless, because iOS ignores the album anyways. So maybe NatShare should be adapted to reflect this change?

I'm not sure if this change actually affects NatShare. NatShare uses `PHPhotoLibrary` directly, and the process to add items to an album is slightly different. Feel free to create a separate issue for this; I'll try running the test to see if saving to an album works on iOS 14. I can't remember the last time I ran the suite of tests.

**Comment by olokobayusuf** [comment]
[This has been added in NatShare 1.3](https://github.com/natmlx/NatShare/releases/tag/1.3.0).
