### ISSUE TITLE
Pressing "Select Photos" in the iOS Permissions Prompt hangs the app

### ISSUE THREAD

**Issue by blizzard318** [natmlx/NatShare#119]
I created an empty project with 4 things:

1) The NatShare package.
2) An example .jpg inside a StreamingAssets folder
3) A RawImage used for a looping animation to test for if the app hangs.
4) PostProcessBuildIOS script to include NSPhotoLibraryUsageDescription permission.

I have a timer, once I got into the app, I wait 2 seconds and then try to use NatShare to transfer it to my Gallery. It will open up the "Access Your Photos" prompt, if you press "Select Photos..." it will hang the app and nothing else happens.

![117240617-d268a200-ae63-11eb-9be0-787eead1d3ea](https://user-images.githubusercontent.com/6711831/125608866-739b25d0-304f-40b7-b01d-81f08629e4f5.png)

I've attached my project.
[Example.zip](https://github.com/natsuite/NatShare/files/6431692/Example.zip)

EDIT: The .jpg transferred to the Gallery fine, but it also still hangs the app regardless.

**Comment by olokobayusuf** [comment]
Fixed in next update, `1.2.6`.
