### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by bariskes11** [natmlx/NatShare#130]
When I download UPM package  I get a very simple "(" error please some one fix that syntax error

**Comment by olokobayusuf** [comment]
Hm can you share the full error, along with your `manifest.json`?

**Comment by bariskes11** [comment]
Ok here is Json 
![image](https://user-images.githubusercontent.com/59174880/177865031-09eb039d-297a-4d9a-bcb1-08e48dd33b62.png)

Error is very simple  you'll see it right away after you download the package 

![image](https://user-images.githubusercontent.com/59174880/177864738-2548d641-2a73-4b40-8b6a-1f55432e9ff2.png)

**Comment by olokobayusuf** [comment]
You didn't close the `scopedRegistries` array. You are missing a "]" before the last "}".

**Comment by bariskes11** [comment]
Hi hello same error stil exists
![image](https://user-images.githubusercontent.com/59174880/177994727-5b8c4a53-2bab-4647-9d6b-db509c5e1dc8.png)
I took the  wrong screen show of Json

**Comment by olokobayusuf** [comment]
Can you share the full JSON text instead of a screenshot?
